### PR TITLE
functionality for color based on infection type

### PR DESCRIPTION
**Pull request by Brendan-Lawton**

### CODE REVIEW

**Comment by billyc** [comment]
Before merging this, just a question - does this impact performance at all or is the dataset small enough it doesn't matter?

Because now the calls to `getColor` are doing logic (albeit just a simple if statement). I just want to make sure that the map is still smooth and nice looking.

**Comment by Brendan-Lawton** [comment]
@billyc the data sets seem to be relatively small so it doesn't impact performance (I was testing with their regular output data and it loaded very quickly).

**Comment by billyc** [comment]
I've merged it, want me to push it to prod or is there more coming?

**Comment by Brendan-Lawton** [comment]
you can push it to prod! Thanks!

**Pull request merged**
